# Generated by Django 4.2.5 on 2023-10-13 05:21

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0021_rename_rfi_document_serviceprovider_rfidoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ein',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
